spring.application.name=opsflow-api

spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/opsflow
spring.datasource.username=opsflow
spring.datasource.password=opsflow_dev_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
